redpanda-data/rp-connect-docs

modules/guides/pages/getting_started.adoc

Users can pull the Redpanda Docker image, which comes with `rpk` in order to run Redpanda Connect with `rpk connect`.

Add Docker to get started

---

modules/components/pages/inputs/aws_s3.adoc

Fix originally applied in https://github.com/redpanda-data/connect/pull/2603

Point S3 input documentation to scanner instead of codec

---

antora.yml
modules/configuration/pages/about.adoc
modules/configuration/pages/interpolation.adoc
modules/configuration/pages/resources.adoc
modules/configuration/pages/secrets.adoc
modules/configuration/pages/templating.adoc
modules/configuration/pages/unit_testing.adoc
modules/configuration/pages/using_cue.adoc
modules/cookbooks/pages/discord_bot.adoc
modules/guides/pages/bloblang/about.adoc
modules/guides/pages/bloblang/walkthrough.adoc
modules/guides/pages/getting_started.adoc
modules/guides/pages/streams_mode/about.adoc
modules/guides/pages/streams_mode/using_config_files.adoc
modules/guides/pages/streams_mode/using_rest_api.adoc

Fix `rpk connect` commands

---

modules/guides/pages/getting_started.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2531
Review deadline: 12 June

Use interactive mode in Docker command

---

antora.yml
package-lock.json

Requires this to merged first https://github.com/redpanda-data/docs-extensions-and-macros/pull/55

Add enterprise connectors

---

modules/ROOT/pages/about.adoc
modules/components/pages/about.adoc
modules/components/pages/buffers/about.adoc
modules/components/pages/inputs/about.adoc
modules/components/pages/outputs/about.adoc
modules/configuration/pages/about.adoc
modules/configuration/pages/resources.adoc
modules/guides/pages/bloblang/about.adoc
modules/guides/pages/getting_started.adoc
modules/guides/pages/index.adoc
modules/guides/pages/streams_mode/about.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2553
Review deadline: 15 July
URLs that never existed have been excluded
[Homepage](https://deploy-preview-19--redpanda-connect.netlify.app//redpanda-connect/about/)
```
https://docs.redpanda.com/redpanda-connect/components/ > /components/about
https://docs.redpanda.com/redpanda-connect/components/conditions/ > /components/about
https://docs.redpanda.com/redpanda-connect/components/buffers/ > /components/buffers/about
https://docs.redpanda.com/redpanda-connect/components/outputs/ > /components/outputs/about
https://docs.redpanda.com/redpanda-connect/components/inputs > /components/inputs/about
https://docs.redpanda.com/redpanda-connect/getting_started/overview > /guides/getting_started/ …
```

#2533 RP Connect redirects

---

antora.yml

Part of https://github.com/redpanda-data/documentation-private/issues/2587
- Renames the component to 'Connect' so that the UI displays it instead of 'Redpanda Connect'.
- Specifies the order that this component should be displayed in the docs header and the color of the header.

Rename component to Connect

---

antora.yml

Marks the various new AI processors as enterprise licensed.
???

Mark AI processors as enterprise

---

.github/workflows/build.yml

fixes: https://redpandadata.atlassian.net/browse/PESDLC-1737
follow-up to PR #25 to address [error](https://github.com/redpanda-data/rp-connect-docs/actions/runs/10229979034/job/28304348004#step:2:56) on action run after merge to `main`:
> Error: Credentials could not be loaded, please check your action inputs
N/A

gha: fix configure-aws-credentials

---

modules/configuration/pages/about.adoc
modules/configuration/pages/interpolation.adoc
modules/configuration/pages/resources.adoc
modules/configuration/pages/secrets.adoc
modules/configuration/pages/using_cue.adoc
modules/cookbooks/pages/discord_bot.adoc
modules/guides/pages/streams_mode/using_config_files.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2636
Review deadline: 7 Aug
[Configuration](https://deploy-preview-27--redpanda-connect.netlify.app/redpanda-connect/configuration/about/)
[Interpolation](https://deploy-preview-27--redpanda-connect.netlify.app/redpanda-connect/configuration/interpolation/)
[Resources](https://deploy-preview-27--redpanda-connect.netlify.app/redpanda-connect/configuration/resources/)
[Secrets](https://deploy-preview-27--redpanda-connect.netlify.app/redpanda-connect/configuration/secrets/)
[Using CUE](https://deploy-preview-27--redpanda-connect.netlify.app/redpanda-connect/configuration/using_cue/)
[Streams mode](https://deploy-preview-27--redpanda-connect.netlify.app/redpanda-connect/guides/streams_mode/about/)
[Create a Discord …

2636 Incorrect syntax in streams mode and -c flag removed

---

.github/workflows/update-extensions.yml

Whenever we update our extensions in https://github.com/redpanda-data/docs-extensions-and-macros, we need to remember to manually do npm update @redpanda-data/docs-extensions-and-macros to get the latest changes in all our local builds. This PR adds a GH Action that can be triggered manually or automatically every time a new extension version is released. The action runs npm update @redpanda-data/docs-extensions-and-macros and submits a pull request to the respective branches.

Add automation for npm update

---

modules/cookbooks/pages/rag.adoc

Fixes missing content in Compute the embeddings section of the Cloud version of this content: https://deploy-preview-62--rp-cloud.netlify.app/redpanda-cloud/develop/connect/cookbooks/rag/
Review deadline: 12
N/A. This content is not visible in the page preview.

2540 Fix content in Cloud version of the AI cookbook

---

modules/ROOT/nav.adoc
modules/cookbooks/pages/kafka_migrator.adoc

Add a cookbook to demo the new Kafka Migrator feature: https://github.com/redpanda-data/connect/pull/2789
TODO:
Review deadline: September 9th
https://deploy-preview-36--redpanda-docs-preview.netlify.app/current/modules/cookbooks/pages/kafka_migrator

Add Kafka Migrator cookbook

---

modules/cookbooks/pages/kafka_migrator.adoc

Remove templating link as not relevant to Cloud users and doesn't support self-managed use case.
Review deadline: 12 September

2540 - Remove templating link

---

modules/components/pages/inputs/kafka_migrator.adoc
modules/components/pages/inputs/kafka_migrator_bundle.adoc
modules/components/pages/outputs/kafka_migrator.adoc
modules/components/pages/outputs/kafka_migrator_bundle.adoc
modules/cookbooks/pages/kafka_migrator.adoc

This was raised as a requirement from the Apache Kafka team for copyright reasons:
https://redpandadata.slack.com/archives/C076AV2M5MH/p1726670549775749
AS: I have checked with David Foley and no trademark symbol is required.
Review deadline: 20 September
https://deploy-preview-59--redpanda-connect.netlify.app/redpanda-connect/cookbooks/kafka_migrator/
https://deploy-preview-59--redpanda-connect.netlify.app/redpanda-connect/components/inputs/kafka_migrator/
https://deploy-preview-59--redpanda-connect.netlify.app/redpanda-connect/components/inputs/kafka_migrator_bundle/
https://deploy-preview-59--redpanda-connect.netlify.app/redpanda-connect/components/outputs/kafka_migrator/ …

Use Apache Kafka in the Kafka Migrator cookbook.

---

modules/components/pages/caches/gcp_cloud_storage.adoc
modules/components/pages/inputs/gcp_bigquery_select.adoc
modules/components/pages/inputs/gcp_cloud_storage.adoc
modules/components/pages/inputs/gcp_pubsub.adoc
modules/components/pages/outputs/gcp_bigquery.adoc
modules/components/pages/outputs/gcp_cloud_storage.adoc
modules/components/pages/outputs/gcp_pubsub.adoc
modules/components/pages/processors/gcp_bigquery_select.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2735
Review deadline: 20 September
[gcp_cloud_storage (cache)](https://deploy-preview-60--redpanda-connect.netlify.app/redpanda-connect/components/caches/gcp_cloud_storage/)
[gcp_bigquery_select (input)](https://deploy-preview-60--redpanda-connect.netlify.app/redpanda-connect/components/inputs/gcp_bigquery_select/)
[gcp_cloud_storage (input)](https://deploy-preview-60--redpanda-connect.netlify.app/redpanda-connect/components/inputs/gcp_cloud_storage/)
[gcp_pubsub (input)](https://deploy-preview-60--redpanda-connect.netlify.app/redpanda-connect/components/inputs/gcp_pubsub/)
[gcp_bigquery_select (output)](https://deploy-preview-60--redpanda-connect.netlify.app/redpanda-connect/components/outputs/gcp_bigquery/) …

Add credentials_json field to GCP Connectors

---

modules/cookbooks/pages/redpanda_migrator.adoc

We need to set `replication_factor_override: false` because the default behaviour is to have topics created with replication factor set to `3` and that is not compatible with having a single Redpanda Docker container. This fix is only needed for the localhost setup.
This fix and the rename of `kafka_migrator_bundle` to `redpanda_migrator_bundle` should also be applied to the blog post: https://www.redpanda.com/blog/kafka-migrator-redpanda-connect. We should probably also adjust its URL if it's possible to do it without breaking existing links.
Review deadline: 9th October.

Fix Redpanda Migrator cookbook

---

modules/components/pages/inputs/kafka_franz.adoc
modules/components/pages/inputs/nats.adoc
modules/components/pages/inputs/redpanda_migrator.adoc
modules/components/pages/inputs/redpanda_migrator_bundle.adoc
modules/components/pages/inputs/schema_registry.adoc
modules/components/pages/outputs/aws_s3.adoc
modules/components/pages/outputs/gcp_bigquery.adoc
modules/components/pages/outputs/nats.adoc
modules/components/pages/outputs/redpanda_migrator.adoc
modules/components/pages/outputs/redpanda_migrator_bundle.adoc
modules/components/pages/outputs/schema_registry.adoc
modules/components/pages/processors/aws_bedrock_chat.adoc
modules/components/pages/processors/gcp_vertex_ai_chat.adoc
modules/components/partials/feature_stability_caution.adoc
modules/guides/pages/bloblang/methods.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2744
Review deadline: 10th October
Added `content_md5` field to [aws_s3 output](https://deploy-preview-65--redpanda-connect.netlify.app/redpanda-connect/components/outputs/aws_s3/?tab=tabs-1-advanced)
Added `send_ack` field to [nats_input](https://deploy-preview-65--redpanda-connect.netlify.app/redpanda-connect/components/inputs/nats/#send_ack)
Added auth fields to [schema_registry input](https://deploy-preview-65--redpanda-connect.netlify.app/redpanda-connect/components/inputs/schema_registry/#oauth) and [schema_registry output](https://deploy-preview-65--redpanda-connect.netlify.app/redpanda-connect/components/outputs/schema_registry/#oauth-enabled)
Added `job_project` to [gcp_bigquery …

DOC-600 Field level changes for release v.4.31 to v.4.37.0

---

modules/components/pages/inputs/http_server.adoc

https://redpandacommunity.slack.com/archives/C075M18MAEA/p1728753394495179?thread_ts=1728740922.545079&cid=C075M18MAEA
I was having a hard time figuring out how headers were being translated into connect based on the existing documentation. This should help in the future.

Update http_server.adoc to talk about headers more.

---

modules/cookbooks/pages/redpanda_migrator.adoc

Resolves: [DOC-643](https://redpandadata.atlassian.net/browse/DOC-643)
Review deadline: 18 October
Updates `redpanda-connect` to `rpk connect` in commands.
https://deploy-preview-74--redpanda-connect.netlify.app/redpanda-connect/cookbooks/redpanda_migrator/
https://deploy-preview-74--redpanda-connect.netlify.app/redpanda-cloud/develop/connect/cookbooks/redpanda_migrator/
[DOC-643]: https://redpandadata.atlassian.net/browse/DOC-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-643 Update commands in Redpanda Migrator Cookbook

---

modules/ROOT/nav.adoc
modules/components/pages/outputs/amqp_0_9.adoc
modules/components/pages/outputs/azure_data_lake_gen2.adoc

Resolves [DOC-667](https://redpandadata.atlassian.net/browse/DOC-667)
Review deadline: 31st October
Cloud version is enabled in this PR: https://github.com/redpanda-data/cloud-docs/pull/101
[azure_data_lake_gen2 output](https://deploy-preview-78--redpanda-connect.netlify.app/redpanda-connect/components/outputs/azure_data_lake_gen2/)
[DOC-667]: https://redpandadata.atlassian.net/browse/DOC-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-667 Azure Data Lake Gen2 output

---

modules/components/pages/caches/sql.adoc
modules/components/pages/inputs/sql_raw.adoc
modules/components/pages/inputs/sql_select.adoc
modules/components/pages/outputs/sql_insert.adoc
modules/components/pages/outputs/sql_raw.adoc
modules/components/pages/processors/sql_insert.adoc
modules/components/pages/processors/sql_raw.adoc
modules/components/pages/processors/sql_select.adoc
modules/components/partials/drivers_note.adoc

Resolves: [DOC-370](https://redpandadata.atlassian.net/browse/DOC-370)
Review deadline: 7th November
- Resolves formatting error. In DSN field, text after `&` was incorrectly highlighted. Fix is to enclose value in quotes as still valid YAML.
- Updates format of note under drivers table and pulls this into a partial for easier management/maintenance.
- [`sql` cache](https://deploy-preview-87--redpanda-connect.netlify.app/redpanda-connect/components/caches/sql/)
- [`sql_raw` input](https://deploy-preview-87--redpanda-connect.netlify.app/redpanda-connect/components/inputs/sql_raw/)
- [`sql_select` input](https://deploy-preview-87--redpanda-connect.netlify.app/redpanda-connect/components/inputs/sql_select/)
- [`sql_insert` output](https://deploy-preview-87--redpanda-connect.netlify.app/redpan …

DOC-370 Fix SQL tagging and style issues

---

modules/ROOT/nav.adoc
modules/components/pages/inputs/timeplus.adoc
modules/components/pages/outputs/timeplus.adoc

Resolves [DOC-734](https://redpandadata.atlassian.net/browse/DOC-734)
Review deadline: 14 November
Part of docs release for v4.39.0.
Associated PR adds this connector to the Cloud docs: https://github.com/redpanda-data/cloud-docs/pull/117
[`timeplus` input](https://deploy-preview-91--redpanda-connect.netlify.app/redpanda-connect/components/inputs/timeplus/)
[DOC-734]: https://redpandadata.atlassian.net/browse/DOC-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-734 Add new timeplus input

---

modules/guides/pages/bloblang/arithmetic.adoc

Fixes https://github.com/redpanda-data/connect/issues/3029
It does look OK with this change, but I don't really understand why that `+` character needs to be escaped that way. I figured it out via https://stackoverflow.com/questions/63917351/how-to-escape-double-plus-plus-sign-in-asciidoctor-asciidoc.
Review deadline: N/A
- [+] Small fix (typos, links, copyedits, etc)

Fix formatting bug

---

modules/components/pages/inputs/cassandra.adoc
modules/components/pages/inputs/kafka.adoc
modules/components/pages/inputs/kafka_franz.adoc
modules/components/pages/inputs/redpanda.adoc
modules/components/pages/inputs/redpanda_common.adoc
modules/components/pages/inputs/redpanda_migrator.adoc
modules/components/pages/inputs/schema_registry.adoc
modules/components/pages/outputs/aws_dynamodb.adoc
modules/components/pages/outputs/aws_kinesis.adoc
modules/components/pages/outputs/aws_kinesis_firehose.adoc
modules/components/pages/outputs/aws_sqs.adoc
modules/components/pages/outputs/cassandra.adoc
modules/components/pages/outputs/elasticsearch.adoc
modules/components/pages/outputs/kafka.adoc
modules/components/pages/outputs/kafka_franz.adoc
modules/components/pages/outputs/ockam_kafka.adoc
modules/components/pages/outputs/redpanda.adoc
modules/components/pages/outputs/redpanda_common.adoc
modules/components/pages/outputs/redpanda_migrator.adoc
modules/components/pages/outputs/redpanda_migrator_offsets.adoc
modules/components/pages/outputs/retry.adoc
modules/components/pages/outputs/schema_registry.adoc
modules/components/pages/processors/redpanda_data_transform.adoc
modules/components/pages/processors/retry.adoc
modules/components/pages/processors/schema_registry_decode.adoc
modules/components/pages/processors/schema_registry_encode.adoc

Resolves [https://github.com/redpanda-data/documentation-private/issues/<add-your-issue-number-here>](https://redpandadata.atlassian.net/browse/DOC-778)
Review deadline: 2nd December
Includes all changes in v4.40.0 for related Kafka components, including:
- Changes to timestamps from `timestamp` to `timestamp_ms` including updates to metadata fields
- New schema and backfill fields
- Update to Schema registry client
- Addition of metadata_max-age to `redpanda_migrator_offsets` output
**Inputs**
[kafka](https://deploy-preview-107--redpanda-connect.netlify.app/redpanda-connect/components/inputs/kafka/)
[kafka_franz](https://deploy-preview-107--redpanda-connect.netlify.app/redpanda-connect/components/inputs/kafka_franz/)
[redpanda](https://deploy-preview-107--redpanda-connect.netlify.app/redp …

DOC-778 Updates to Kafka components

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves [https://github.com/redpanda-data/documentation-private/issues/<add-your-issue-number-here>](https://redpandadata.atlassian.net/browse/DOC-778)
Review deadline: 27 November
Includes:
- Changes to `max_in_flight` default 
- New build options
- `schema_evolution` set to `true` in example to autocreate tables
- Updates to `account` field description
[snowflake_streaming output](https://deploy-preview-108--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)

DOC-778 Updates to snowflake_streaming output

---

modules/components/pages/inputs/pg_stream.adoc

Fix typo in pg_stream doc

---

modules/ROOT/nav.adoc
modules/components/pages/processors/benchmark.adoc

Resolves [DOC-849](https://redpandadata.atlassian.net/browse/DOC-849)
Review deadline: 11th December
Related PR to add the same content to Cloud docs: https://github.com/redpanda-data/cloud-docs/pull/151
[`benchmark` processor](https://deploy-preview-125--redpanda-connect.netlify.app/redpanda-connect/components/processors/benchmark/)
[DOC-849]: https://redpandadata.atlassian.net/browse/DOC-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-849 Add benchmark processor to Self-Managed

---

modules/components/pages/outputs/sql.adoc

I found the link on https://docs.redpanda.com/redpanda-connect/components/outputs/sql/#alternatives go back to sql instead of the expected sql_insert page
[https://deploy-preview-135--redpanda-connect.netlify.app/redpanda-connect/components/outputs/sql/#alternatives](https://deploy-preview-135--redpanda-connect.netlify.app/redpanda-connect/components/outputs/sql/#alternatives)

Update sql.adoc to refer to sql_insert instead of sql

---

modules/components/pages/redpanda/about.adoc
modules/components/partials/enterprise_component_note.adoc
modules/components/partials/enterprise_feature_note.adoc
modules/configuration/pages/allow_and_deny_lists.adoc
modules/configuration/pages/secrets.adoc
modules/get-started/pages/licensing.adoc

Resolves [DOC-810](https://redpandadata.atlassian.net/browse/DOC-810), [DOC-835](https://redpandadata.atlassian.net/browse/DOC-835)
Review deadline: 20th December
For consistent messaging > related PRs: [https://github.com/redpanda-data/docs/pull/930](https://github.com/redpanda-data/docs/pull/930) and [https://github.com/redpanda-data/docs-extensions-and-macros/pull/89](https://github.com/redpanda-data/docs-extensions-and-macros/pull/89)
[Enterprise Licensing](https://deploy-preview-137--redpanda-connect.netlify.app/redpanda-connect/get-started/licensing/). Links from the table show each enterprise feature marked with a note.
[DOC-810]: https://redpandadata.atlassian.net/browse/DOC-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-835]: …

DOC-810 Tag enterprise features

---

package-lock.json
package.json

Review deadline: 10 Jan
Using `latest` is considered bad practice because we could auto-update to a version with breaking changes.
This PR specifies a range that allows upgrades to new minor and patch versions.

Specify a valid semver range for extensions package

---

modules/components/pages/outputs/amqp_1.adoc

Resolves [DOC-905](https://redpandadata.atlassian.net/browse/DOC-905), and minor style updates
Review deadline: 14th January
[ampq_1 output](https://deploy-preview-144--redpanda-connect.netlify.app/redpanda-connect/components/outputs/amqp_1/#content_type)
[DOC-905]: https://redpandadata.atlassian.net/browse/DOC-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-905 Add content_type field to amqp_1 output

---

modules/components/pages/processors/javascript.adoc

Resolves [DOC-909](https://redpandadata.atlassian.net/browse/DOC-909). Also, includes minor style updates.
Review deadline: 14th January
[`javascript` processor](https://deploy-preview-143--redpanda-connect.netlify.app/redpanda-connect/components/processors/javascript/)
[DOC-909]: https://redpandadata.atlassian.net/browse/DOC-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-909 Interpolation support removed for fields in javascript processor

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves [DOC-907](https://redpandadata.atlassian.net/browse/DOC-907)
Review deadline: 23rd January
[`snowflake_streaming` output](https://deploy-preview-155--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)
[DOC-907]: https://redpandadata.atlassian.net/browse/DOC-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-907 Changes to snowflake_streaming output for exactly-once delivery

---

local-antora-playbook.yml
package-lock.json
package.json

For details, see https://redpandadata.atlassian.net/wiki/spaces/DOC/pages/1051328557/Mermaid+diagrams

Add mermaid diagram support for local builds

---

modules/components/pages/outputs/snowflake_streaming.adoc
modules/cookbooks/pages/snowflake_ingestion.adoc

Review deadline: 30th January
**Self-managed**
[snowflake_streaming output](https://deploy-preview-163--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)
[snowflake cookbook](https://deploy-preview-163--redpanda-connect.netlify.app/redpanda-connect/cookbooks/snowflake_ingestion/)
**Cloud**
[snowflake_streaming output](https://deploy-preview-163--redpanda-connect.netlify.app/redpanda-cloud/develop/connect/components/outputs/snowflake_streaming/)
[snowflake cookbook](https://deploy-preview-163--redpanda-connect.netlify.app/redpanda-cloud/develop/connect/cookbooks/snowflake_ingestion/)

DOC-987 Add crosslinking between snowflake_streaming assets

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves [DOC-972](https://redpandadata.atlassian.net/browse/DOC-972)
Review deadline: 4th February
Related PR for Cloud: [https://github.com/redpanda-data/cloud-docs/pull/195](https://github.com/redpanda-data/cloud-docs/pull/195)
[`snowflake_streaming` output](https://deploy-preview-168--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)
[DOC-972]: https://redpandadata.atlassian.net/browse/DOC-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-972 Remove beta attribute from snowflake_streaming output

---

modules/components/pages/processors/log.adoc

We don't support `ALL`.
Matching Benthos PR: https://github.com/redpanda-data/benthos/pull/174

Fix the values for the level field of the log processor

---

modules/components/pages/outputs/kafka_franz.adoc
modules/components/pages/outputs/ockam_kafka.adoc
modules/components/pages/outputs/redpanda.adoc
modules/components/pages/outputs/redpanda_migrator.adoc
modules/components/pages/outputs/redpanda_migrator_offsets.adoc

Resolves [DOC-1000](https://redpandadata.atlassian.net/browse/DOC-1000) **and additional changes in [DOC-988](https://redpandadata.atlassian.net/browse/DOC-988)**
Review deadline: 18th February
Outputs
[kafka_franz](https://deploy-preview-167--redpanda-connect.netlify.app/redpanda-connect/components/outputs/kafka_franz/)
[ockam_kafka](https://deploy-preview-167--redpanda-connect.netlify.app/redpanda-connect/components/outputs/ockam_kafka/)
[redpanda](https://deploy-preview-167--redpanda-connect.netlify.app/redpanda-connect/components/outputs/redpanda/)
[redpanda_migrator](https://deploy-preview-167--redpanda-connect.netlify.app/redpanda-connect/components/outputs/redpanda_migrator/)
[redpanda_migrator_offsets](https://deploy-preview-167--redpanda-connect.netlify.app/redpanda-connect/compon …

DOC-1000 Kafka outputs default updates

---

modules/components/pages/inputs/postgres_cdc.adoc

Resolves [DOC-997](https://redpandadata.atlassian.net/browse/DOC-997)
Review deadline: 6th February
[`postgres_cdc` input](https://deploy-preview-169--redpanda-connect.netlify.app/redpanda-connect/components/inputs/postgres_cdc/)
[DOC-997]: https://redpandadata.atlassian.net/browse/DOC-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-997 Add unchanged_toast_value to postgres_cdc

---

modules/components/pages/processors/schema_registry_decode.adoc
modules/components/pages/processors/schema_registry_encode.adoc

Resolves: [DOC-995](https://redpandadata.atlassian.net/browse/DOC-995), [DOC-994](https://redpandadata.atlassian.net/browse/DOC-994) and tries to standardize Avro JSON content
Review deadline: 7th February
Processors:
[schema_registry_decode](https://deploy-preview-170--redpanda-connect.netlify.app/redpanda-connect/components/processors/schema_registry_decode/) with new metadata info and new fields
[schema_registry_encode](https://deploy-preview-170--redpanda-connect.netlify.app/redpanda-connect/components/processors/schema_registry_encode/)
[DOC-995]: https://redpandadata.atlassian.net/browse/DOC-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-994]: https://redpandadata.atlassian.net/browse/DOC-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

DOC-995 Add metadata field and standardize Avro JSON content

---

modules/cookbooks/pages/snowflake_ingestion.adoc

Resolves [DOC-1030](https://redpandadata.atlassian.net/browse/DOC-1030)
Review deadline: 25th February
This pull request includes changes to the `modules/cookbooks/pages/snowflake_ingestion.adoc` file to update the table name used in the Snowflake ingestion configuration.
* Updated the table name from `STREAMING_TABLE` to `STREAMING_DATA` in the Snowflake ingestion configuration. [[1]](diffhunk://#diff-6d8fe9e8bcd006de6be2bb305663c62a2fada4ddf4c9e93ac10a2aae99440c33L188-R188) [[2]](diffhunk://#diff-6d8fe9e8bcd006de6be2bb305663c62a2fada4ddf4c9e93ac10a2aae99440c33L246-R246)
[Ingest data into Snowflake](https://deploy-preview-177--redpanda-connect.netlify.app/redpanda-connect/cookbooks/snowflake_ingestion/)
[DOC-1030]: https://redpandadata.atlassian.net/browse/DOC-1030?atlOrigin=eyJpIjoiNWRkN …

DOC-1030 Fix table name in Snowflake cookbook

---

modules/components/pages/inputs/http_client.adoc
modules/components/pages/inputs/websocket.adoc
modules/components/pages/outputs/http_client.adoc
modules/components/pages/outputs/websocket.adoc
modules/components/pages/processors/http.adoc
modules/components/pages/processors/schema_registry_decode.adoc
modules/components/pages/processors/schema_registry_encode.adoc

Resolves [DOC-768](https://redpandadata.atlassian.net/browse/DOC-768)
Review deadline: 5th March
With related PR adds http components to cloud docs, and brings docs in line with style guide.
Related PR to add these docs to the Cloud docs set: [https://github.com/redpanda-data/cloud-docs/pull/209](https://github.com/redpanda-data/cloud-docs/pull/209)
This pull request includes a number of changes to improve the clarity and consistency of the documentation for the http_client input, output and http processor and related files. The most important changes involve rephrasing sentences for better readability, specifying optional fields, and improving the precision of descriptions.
Documentation improvements:
* Updated various descriptions to be more concise and clear, such as changing "Connects …

DOC-768 Update http components

---

modules/components/pages/inputs/amqp_0_9.adoc
modules/components/pages/outputs/amqp_0_9.adoc

Resolves [DOC-1046](https://redpandadata.atlassian.net/browse/DOC-1046)
Review deadline: 28th February
Adds arguments field to `ampq_09` input and output.
This pull request includes several documentation updates and improvements for the AMQP 0.9 input and output configuration files. The changes aim to clarify descriptions, add optional field indicators, and improve readability.
Documentation improvements:
* [`modules/components/pages/inputs/amqp_0_9.adoc`](diffhunk://#diff-fcfff71368d9393e99f3a23af22505cab6670eef51a841db69c283b36bb2e1d1L24-R30): Updated descriptions for various fields, added optional indicators for fields like `consumer_tag`, `root_cas`, and `root_cas_file`, and improved explanations for `queue_declare`, `auto_ack`, and `nack_reject_patterns`. …

DOC-1046 Add arguments field to amqp_09 input and output

---

modules/components/pages/processors/schema_registry_decode.adoc

Resolves [DOC-1047](https://redpandadata.atlassian.net/browse/DOC-1047)
Review deadline: 28th February
This pull request includes updates to the `schema_registry_decode` documentation to clarify the optional nature of several configuration fields and to introduce a new `mapping` field for custom Avro schema mappings.
Key changes:
Documentation updates:
* [`modules/components/pages/processors/schema_registry_decode.adoc`](diffhunk://#diff-fc62b03da657b2dfa3924d3a7d1f7cf3df3e46e4dbd38b4b5fa0ebc463c31d37R46-R68): Updated several fields (`consumer_key`, `consumer_secret`, `access_token`, `access_token_secret`, `username`, `password`, `private_key_file`, `signing_method`, `root_cas`, `root_cas_file`) to indicate they are optional.
New feature:
* …

DOC-1047 Add Avro mapping field

---

modules/guides/pages/bloblang/functions.adoc

Resolves [DOC-149](https://redpandadata.atlassian.net/browse/DOC-1049)
Review deadline: March 3rd
This pull request adds the `uuid_v7` function to the `modules/guides/pages/bloblang/functions.adoc` file.
New function added:
* [`uuid_v7`](diffhunk://#diff-1c116661660983b92bc8100b36d7c5d44f57104c9add3a0c048d2e461748ef02R337-R356): Generates a new time-ordered UUID each time it is invoked and prints a string representation. This function is useful for scenarios where the exact timing of events is important, such as during data migration or replication. It includes an optional `time` parameter to specify the timestamp used for the UUID.
[Bloglang functions](https://deploy-preview-181--redpanda-connect.netlify.app/redpanda-connect/guides/bloblang/functions/#uuid_v7)
[DOC-149]: …

DOC-1049 Add uuid_v7 bloblang function

---

modules/ROOT/nav.adoc
modules/components/pages/processors/crash.adoc
modules/configuration/pages/error_handling.adoc

Resolves [DOC-1048](https://redpandadata.atlassian.net/browse/DOC-1048)
Review deadline: 6th March
This pull request introduces a new processor called `crash` and updates the documentation to include this new processor and its usage. The changes are primarily focused on adding the `crash` processor to the list of available processors and providing detailed documentation on how to use it for error handling.
* [`modules/components/pages/processors/crash.adoc`](diffhunk://#diff-504a47729d9f2593da38b40360366ecdf22150adf52c5054f6c8c71ff7511ec0R1-R25): Added a new document describing the `crash` processor, its configuration fields, and usage examples. This processor stops the current pipeline process with a fatal log message and is useful for detecting unhandled errors during development and …

DOC-1048 Add crash processor

---

modules/components/pages/inputs/http_client.adoc
modules/components/pages/outputs/http_client.adoc
modules/components/pages/processors/http.adoc

Resolves [DOC-1050](https://redpandadata.atlassian.net/browse/DOC-1050)
Review deadline: 6th March
This pull request adds a new configuration option to disable HTTP/2 in the HTTP client, processor, and output components. The most important changes include the addition of the `disable_http2` option and the corresponding documentation updates.
* Added `disable_http2` option to the HTTP client input configuration. This option allows users to disable HTTP/2, with a default value of `false`. [[1]](diffhunk://#diff-7dc1d29f11c2fd03a73194a4abb259246a809a392b1f5e0125bb3dec571ed265R96) [[2]](diffhunk://#diff-7dc1d29f11c2fd03a73194a4abb259246a809a392b1f5e0125bb3dec571ed265R763-R774)
* Added `disable_http2` option to the HTTP client output configuration. This option allows users to disable HTTP/2, …

DOC-1050 Add disable_http2 field

---

modules/ROOT/nav.adoc
modules/components/pages/inputs/mongodb_cdc.adoc

Resolves [DOC-514](https://redpandadata.atlassian.net/browse/DOC-514)
Review deadline: 7th March
Related PR to enable connector in cloud-docs: https://github.com/redpanda-data/cloud-docs/pull/227
This pull request introduces a new MongoDB CDC (Change Data Capture) input component to the documentation. The most important changes include updating the navigation to include the new component and adding comprehensive documentation for configuring and using the `mongodb_cdc` input.
Updates to documentation:
* [`modules/ROOT/nav.adoc`](diffhunk://#diff-5daf5a85fd51578ad9fc545388bf62176bcea32094ee97b5e30c2eea044e4193R67): Added a reference to the new MongoDB CDC input component in the navigation.
* [`modules/components/pages/inputs/mongodb_cdc.adoc`](diffhunk://#diff-826031304e0d00bc21e9c843f7f631 …

DOC-514 Add mongodb_cdc_connector

---

modules/components/pages/outputs/elasticsearch_v8.adoc

Resolves [DOC-1111](https://redpandadata.atlassian.net/browse/DOC-1111)
Review deadline: 12th March
[elasticsearch_v8 output](https://deploy-preview-191--redpanda-connect.netlify.app/redpanda-connect/components/outputs/elasticsearch_v8/)
[DOC-1111]: https://redpandadata.atlassian.net/browse/DOC-1111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1111 Remove link from note on elasticsearch_v8 output

---

modules/components/pages/inputs/mongodb_cdc.adoc
modules/components/pages/inputs/mysql_cdc.adoc

Resolves [DOC-1128](https://redpandadata.atlassian.net/browse/DOC-1128)
Review deadline: 18 March
This pull request makes minor changes to the `mongodb_cdc` and `mysql_cdc` documentation to remove the beta status from both files.
Related cloud-docs PR: [https://github.com/redpanda-data/cloud-docs/pull/235](https://github.com/redpanda-data/cloud-docs/pull/235)
- [`mongodb_cdc` input](https://deploy-preview-195--redpanda-connect.netlify.app/redpanda-connect/components/inputs/mongodb_cdc/)
- [`mysql_cdc` input](https://deploy-preview-195--redpanda-connect.netlify.app/redpanda-connect/components/inputs/mysql_cdc/)
[DOC-1128]: https://redpandadata.atlassian.net/browse/DOC-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1128 Remove beta flags mongodb_cdc and mysql_cdc connectors

---

modules/components/pages/inputs/postgres_cdc.adoc

Resolves [DOC-1130](https://redpandadata.atlassian.net/browse/DOC-1130)
Review deadline: 19 March
The change removes the `:page-beta:` attribute to indicate that the page is no longer in beta.
Related PR to remove beta tag from cloud-docs: [https://github.com/redpanda-data/cloud-docs/pull/236](https://github.com/redpanda-data/cloud-docs/pull/236)
[`postgres_cdc` input](https://deploy-preview-199--redpanda-connect.netlify.app/redpanda-connect/components/inputs/postgres_cdc/)
[DOC-1130]: https://redpandadata.atlassian.net/browse/DOC-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1130 Remove beta tag from postgres_cdc connector

---

modules/components/pages/inputs/redpanda_migrator_offsets.adoc
modules/components/pages/outputs/redpanda_migrator_offsets.adoc

Resolves: [DOC-1123](https://redpandadata.atlassian.net/browse/DOC-1123)
Review deadline: 20th March
This pull request includes changes to the `redpanda_migrator_offsets` input and output documentation to add new metadata fields and improve clarity. The most important changes include adding a new metadata field, updating descriptions, and marking certain fields as optional.
* Added `kafka_is_high_watermark` to the list of metadata fields in the `redpanda_migrator_offsets` input documentation.
* Added `is_high_watermark` to the output configuration example in the `redpanda_migrator_offsets` output documentation.
* Revised the description for using the `redpanda_migrator_offsets` output with the `kafka_franz` input for clarity.
* Marked `root_cas`, `root_cas_file`, and `client_certs` as …

DOC-1123 Add is_high_watermark field and metadata

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves [DOC-1119](https://redpandadata.atlassian.net/browse/DOC-1119)
This pull request updates the documentation for Snowflake streaming output metrics in the `modules/components/pages/outputs/snowflake_streaming.adoc` file.
[`snowflake_streaming` output](https://deploy-preview-194--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)
[DOC-1119]: https://redpandadata.atlassian.net/browse/DOC-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1119 Add new metrics for snowflake_streaming output

---

modules/configuration/pages/error_handling.adoc

Add an example of enrichment prior to sending to DLQ

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves [DOC-1118](https://redpandadata.atlassian.net/browse/DOC-1118)
[`snowflake_streaming` output](https://deploy-preview-196--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)
[DOC-1118]: https://redpandadata.atlassian.net/browse/DOC-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1118 Add commit_timeout field to snowflake_streaming output

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves: [DOC-1122 ](https://redpandadata.atlassian.net/browse/DOC-1122)
Review deadline: 24 March
This pull request includes updates to the `snowflake_streaming` output documentation to add support for private link deployments by specifying a custom URL. 
[snowflake_streaming output](https://deploy-preview-197--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/#url)

DOC-1122 Add url field to snowflake_streaming output

---

modules/components/pages/inputs/postgres_cdc.adoc

Resolves [DOC-1125](https://redpandadata.atlassian.net/browse/DOC-1125)
The change is related to a breaking change in the naming convention for PostgreSQL logical replication slots in Redpanda Connect.
Documentation update:
* Added a note indicating that starting from version 4.48.1, replication slot names are no longer created with the prefix `rs_`. Users who want to continue using a replication slot created by an earlier version should manually add the `rs_` prefix to the slot name.
[`postgres_cdc` input](https://deploy-preview-200--redpanda-connect.netlify.app/redpanda-connect/components/inputs/postgres_cdc/)
[DOC-1125]: https://redpandadata.atlassian.net/browse/DOC-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

DOC-1125 Add note about replication slot prefix

---

modules/components/pages/outputs/redpanda_migrator.adoc

Resolves [DOC-1131](https://redpandadata.atlassian.net/browse/DOC-1131)
This pull request includes a change to the `modules/components/pages/outputs/redpanda_migrator.adoc` file to clarify the behavior of the `redpanda_migrator` output when handling topics and ACLs.
Documentation update:
* [`modules/components/pages/outputs/redpanda_migrator.adoc`](diffhunk://#diff-8ac53c4414b1931639c3db5e6efce57d9a764192bd996f242084a3d4a30aebc4L87-R89): Clarified that if the destination broker already has the topic, only the missing ACLs are migrated, and if the topic does not exist, it is created along with its ACLs.
[`redpanda_migrator` output](https://deploy-preview-203--redpanda-connect.netlify.app/redpanda-connect/components/outputs/redpanda_migrator/)
[DOC-1131]: …

DOC-1131 Update description of ACL migration for redpanda_migrator output

---

modules/get-started/pages/licensing.adoc

Resolves [DOC-1116](https://redpandadata.atlassian.net/browse/DOC-1116)
This pull request includes updates to the licensing documentation to improve clarity and provide additional instructions for applying and verifying a Redpanda license.
Documentation improvements:
* Clarified the instructions for setting the `REDPANDA_LICENSE_FILEPATH` environment variable by removing unnecessary syntax.
* Updated the section title from "Apply the license using an inline license string" to "Apply the license using a license string" for better readability.
* Added an alternative method for applying a license if a license key file is not available, including setting the `REDPANDA_LICENSE` environment variable.
* Provided an example log output to help users verify the license …

DOC-1116 Load license enterprise license key from environment variable

---

modules/cookbooks/pages/enrichments.adoc

Review deadline: None
Fix minor typo after reading docs to learn more about Redpanda Connect. Note I've not actually run this pipeline, just researching at the moment.
To reflect what's written in https://github.com/redpanda-data/rp-connect-docs/pull/190/files#diff-ac328a354b8ea434d71a388fd8634f4c580394eeccb6a45d1534565346f05465R224

docs: `result_map` writes to document `fake_news_score`

---

modules/components/pages/inputs/ockam_kafka.adoc

See details here: https://github.com/redpanda-data/connect/blob/main/docs/modules/components/pages/inputs/ockam_kafka.adoc

Fix docs for the ockam_kafka input

---

modules/components/pages/outputs/snowflake_streaming.adoc

Resolves DOC-1190
Review deadline: 8th April
This pull request includes an update to the documentation for Snowflake streaming outputs. The change clarifies the handling of special values for the `FLOAT` data type.
Documentation update:
* [`modules/components/pages/outputs/snowflake_streaming.adoc`](diffhunk://#diff-9434ac7730044d18599791222d3586f570c7fd47822805f631eb6c46c4b3b4ffL213-R213): Updated the `FLOAT` data type description to include special values such as `NaN` (Not a Number), `-inf` (negative infinity), and `inf` (positive infinity).
[`snowflake_streaming` output](https://deploy-preview-214--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)

DOC-1190 Extend support for FLOAT values in snowflake_streaming output

---

modules/components/pages/outputs/redpanda_migrator.adoc
modules/components/pages/outputs/redpanda_migrator_bundle.adoc
modules/components/pages/outputs/schema_registry.adoc

Resolves [DOC-1215](https://redpandadata.atlassian.net/browse/DOC-1215)
Review deadline: 9th April
This pull request includes changes to the `redpanda_migrator`, `redpanda_migrator_bundle`, and `schema_registry` output configurations. The most important changes involve updating the `translate_schema_ids` and `translate_ids` fields to provide clearer descriptions and modify their default values.
Updates to `translate_schema_ids` field:
* [`modules/components/pages/outputs/redpanda_migrator.adoc`](diffhunk://#diff-8ac53c4414b1931639c3db5e6efce57d9a764192bd996f242084a3d4a30aebc4L75-R75): Changed the `translate_schema_ids` field default value from `true` to `false` and updated the description to clarify its function. [[1]](diffhunk://#diff-8ac53c4414b1931639c3db5e6efce57d9a764192bd996f242084a3 …

DOC-1215 Add translate ID fields to migrator and schema_registry outputs

---

modules/components/pages/inputs/sftp.adoc
modules/components/pages/outputs/sftp.adoc

Resolves [DOC-1233](https://redpandadata.atlassian.net/browse/DOC-1233)
Review deadline: 14th April
This pull request includes updates to the SFTP input and output documentation to improve clarity and provide additional details on configuration fields.
* [`modules/components/pages/inputs/sftp.adoc`](diffhunk://#diff-756b688eae27f6173648729c5612ea14546edb32611c88f9732977fa3431dcd0L26-R36): Updated descriptions for configuration fields, including specifying that certain fields like `username`, `password`, `private_key_file`, `private_key`, and `private_key_pass` are optional and have no defaults. Enhanced descriptions for `address` and `credentials` fields to provide more clarity. [[1]](diffhunk://#diff-756b688eae27f6173648729c5612ea14546edb32611c88f9732977fa3431dcd0L26-R36) …

DOC-1233 Add private_key field to SFTP input and output

---

.github/workflows/update-extensions.yml

Review deadline: May 2
This pull request updates the `.github/workflows/update-extensions.yml` workflow to improve the process for updating the `@redpanda-data/docs-extensions-and-macros` package. Key changes include modifying permissions, simplifying branch handling, and replacing manual commits with an automated pull request creation step.
* Updated permissions for the `update-dependency` job to include `pull-requests: write` and changed `contents` permission from `read` to `write` to enable pull request creation.
* Replaced the matrix strategy for branches with a fixed reference to the `main` branch, simplifying the workflow.
* Added a step to use the `peter-evans/create-pull-request@v6` action to automate the creation of pull requests for dependency updates, replacing the previous …

Open pull requests to update packages

---

modules/components/pages/inputs/socket_server.adoc

Resolves [DOC-1321](https://redpandadata.atlassian.net/browse/DOC-1321)
Review deadline: 8 May
This pull request adds a new configuration option, `tls.client_auth`, to the `socket_server` input module documentation. This option allows users to specify how client authentication is handled when using TLS, enhancing flexibility and security.
* [`modules/components/pages/inputs/socket_server.adoc`](diffhunk://#diff-8b8f4e52f2a4df9e6fbf1d34e10857dd4f388f7be35d8f663d8c916f02bafe3aR108-R139): Added the `tls.client_auth` option with detailed descriptions of its purpose, type, default value, and available options. This option specifies how client certificates are handled during TLS connections, with choices like `no`, `request`, `require_valid`, `require_any`, and `verify_if_given`. It requires …

DOC-1321 Add `client_auth` field to socket_server input

---

modules/guides/pages/bloblang/methods.adoc

Resolves [DOC-1322](https://redpandadata.atlassian.net/browse/DOC-1322)
Review deadline: 9th May
This pull request updates the Bloblang documentation to replace references to `uuid_v4` with `uuid_v5` and adds a new section documenting the `uuid_v5` method. These changes improve the clarity and functionality of the documentation for users working with name-based UUIDs.
* Replaced all instances of `uuid_v4` with `uuid_v5` in code examples to reflect the usage of name-based UUIDs instead of randomly generated ones. (`modules/guides/pages/bloblang/methods.adoc`: [[1]](diffhunk://#diff-18236ccceeea3b158822ef572ddc0937734f985206891d27e31a4e9121e7933eL11-R11) [[2]](diffhunk://#diff-18236ccceeea3b158822ef572ddc0937734f985206891d27e31a4e9121e7933eL76-R76) …

DOC-1322 Add uuid_v5 Bloblang method

---

modules/components/pages/outputs/redpanda_migrator.adoc

Resolves [DOC-1317](https://redpandadata.atlassian.net/browse/DOC-1317)
Review deadline: 15 May
This pull request introduces a new configuration option, `topic_prefix`, to the Redpanda Migrator documentation. The change allows users to specify a prefix for migrated topic names, enhancing flexibility in topic naming.
* [`modules/components/pages/outputs/redpanda_migrator.adoc`](diffhunk://#diff-8ac53c4414b1931639c3db5e6efce57d9a764192bd996f242084a3d4a30aebc4R73): Added a new configuration field, `topic_prefix`, which allows users to prepend a specified string to the names of migrated topics. This field supports interpolation functions and has a default value of an empty string. [[1]](diffhunk://#diff-8ac53c4414b1931639c3db5e6efce57d9a764192bd996f242084a3d4a30aebc4R73) …

DOC-1317 Adds topic_prefix field to redpanda_migrator output

---

modules/components/pages/inputs/aws_kinesis.adoc
modules/components/pages/inputs/aws_s3.adoc

Resolves [DOC-1315](https://redpandadata.atlassian.net/browse/DOC-1315)
Review deadline: 13 May
This pull request updates the AWS Kinesis and AWS S3 input documentation to improve clarity, add missing details, and introduce new configuration options for AWS credentials. The most significant changes include the addition of detailed descriptions for DynamoDB and Kinesis credential fields, updates to existing descriptions for consistency, and minor corrections in the AWS S3 documentation.
* Added detailed descriptions for `dynamodb.credentials`, including fields like `profile`, `id`, `secret`, `token`, `from_ec2_role`, `role`, and `role_external_id`. These fields allow for more granular control over AWS credentials. [[1]](diffhunk://#diff-4351cceebb80c15c78a27a23373ab5b1946dd6368a2bba8c907b2f …

DOC-1315 Add credentials fields to aws_kinesis input

---

modules/components/pages/processors/protobuf.adoc

Resolves [DOC-1312](https://redpandadata.atlassian.net/browse/DOC-1312)
Review deadline: 15 May
This pull request updates the documentation for the Protobuf processor to improve clarity, provide additional details, and structure the content more effectively. The primary changes include rewording for better readability, adding a new section on performance considerations, and expanding the descriptions of configuration fields.
* **Improved clarity and readability**:
- Rephrased explanations for JSON-to-Protobuf and Protobuf-to-JSON conversions to make them more concise and user-friendly. [[1]](diffhunk://#diff-a4d6ada951ca591a8ffb01021b367de90a22d6b9df7bb76b736f6afa235748d1L72-R124) [[2]](diffhunk://#diff-a4d6ada951ca591a8ffb01021b367de90a22d6b9df7bb76b736f6afa235748d1L82-R134) …

DOC-1312 Add use_enum_numbers and general editing

---

modules/ROOT/nav.adoc
modules/components/pages/processors/google_drive_list_labels.adoc

Resolves [DOC-1311](https://redpandadata.atlassian.net/browse/DOC-1311)
Review deadline: 14 May
Related Cloud PR: [https://github.com/redpanda-data/cloud-docs/pull/292](https://github.com/redpanda-data/cloud-docs/pull/292)
This pull request introduces a new processor for Google Drive, `google_drive_list_labels`, and updates the documentation to include it. The most important changes are the addition of the processor's documentation and its inclusion in the navigation structure.
* [`modules/components/pages/processors/google_drive_list_labels.adoc`](diffhunk://#diff-d8d11be79bc3157c2dcb191c34a2cd5ead0376fdbbd3951ab1db1be2d3f486e8R1-R57): Added a new documentation page for the `google_drive_list_labels` processor, detailing its purpose, configuration, authentication methods, and fields. …

DOC-1311 Add google_drive_list_labels processor

---

modules/ROOT/nav.adoc
modules/components/pages/processors/cohere_rerank.adoc

Resolves [DOC-1316](https://redpandadata.atlassian.net/browse/DOC-1316)
Review deadline: 16 May
Related Cloud PR: [https://github.com/redpanda-data/cloud-docs/pull/296](https://github.com/redpanda-data/cloud-docs/pull/296)
This pull request introduces a new processor, `cohere_rerank`, to the documentation. The processor integrates with the Cohere API to rank documents based on their relevance to a specified query. The changes include adding the processor to the navigation and providing detailed documentation about its configuration, metadata, and usage.
* **Navigation Update**:
- Added a reference to the new `cohere_rerank` processor in the navigation file `modules/ROOT/nav.adoc` to make it accessible in the documentation structure.
* **New Processor Documentation**:
- Created a new file …

DOC-1316 Add cohere_rerank processor

---

modules/ROOT/nav.adoc
modules/components/pages/outputs/qdrant.adoc
modules/components/pages/outputs/redpanda.adoc
modules/components/pages/processors/qdrant.adoc

Resolves [DOC-1328](https://redpandadata.atlassian.net/browse/DOC-1328)
Review deadline: 15 May
Related cloud PR: [https://github.com/redpanda-data/cloud-docs/pull/294](https://github.com/redpanda-data/cloud-docs/pull/294)
This pull request introduces a new Qdrant processor to the documentation, along with updates to related files to support its inclusion. The Qdrant processor integrates with the Qdrant vector database, providing configuration options for secure connections, querying, and filtering. Below are the key changes grouped by theme:
* Added a new file `modules/components/pages/processors/qdrant.adoc` to document the Qdrant processor, including its configuration fields (e.g., `grpc_host`, `api_token`, `tls`) and usage examples. This includes support for TLS settings, vector …

DOC-1328 Add qdrant processor

---

modules/components/partials/fields/processors/parquet_encode.adoc

<details><summary>RPCN Connector Generation Output</summary>
✅ Fetched and saved: /home/runner/work/rp-connect-docs/rp-connect-docs/docs-data/connect-4.60.2.json
⏳ Generating connector partials...
⏳ Drafting missing connectors…
No GitHub token found (VBOT_GITHUB_API_TOKEN).
Saved: /tmp/redpanda-connect-csv/info.csv
📥 Loaded CSV from GitHub into: /tmp/redpanda-connect-csv/info.csv
✅ Parsed 302 connector records.
⏳ Docs missing for 1 connectors:
• input/pg_stream
Skipping draft for deprecated component: inputs/pg_stream
📋 RPCN Connector Delta Report
➤ No newly added components.
➤ No newly added fields.
✅ Updated Antora version: 4.60.2
📊 Generation Report:
• Partial files: 340
• Fields partials: 261 total
– modules/components/partials/fields/buffers/memory.adoc
– …

auto-docs: Update RPCN connector docs

---

modules/cookbooks/pages/redpanda_migrator.adoc

This pull request updates the `redpanda_migrator.adoc` documentation to add a new "Limitations" section specifying that Redpanda Migrator cannot migrate schemas between multi-tenant clusters.
Resolves https://redpandadata.atlassian.net/browse/DOC-1543
[Redpanda Migrator](https://deploy-preview-289--redpanda-connect.netlify.app/redpanda-connect/cookbooks/redpanda_migrator/)

DOC-1543 Redpanda Migrator does not support serverless

---

local-antora-playbook.yml

API docs content is now managed in https://github.com/redpanda-data/api-docs

Remove docs:api as content source

---

modules/get-started/pages/licensing.adoc
modules/get-started/pages/quickstarts/helm-chart.adoc

Resolves https://redpandadata.atlassian.net/browse/DOC-819

Add info on configuring the env variable for license using Helm

---

modules/ai-agents/pages/mcp-server/quickstart.adoc

I get 403 authentication errors coming back with the `public` subdomain but not without it. This PR fixes the quickstart to avoid these 403 errors.

Fix MCP quickstart
