redpanda-data/rp-connect-docs

modules/components/pages/inputs/azure_blob_storage.adoc
modules/components/pages/inputs/azure_cosmosdb.adoc
modules/components/pages/outputs/azure_blob_storage.adoc
modules/components/pages/processors/azure_cosmosdb.adoc

Some formatting issues that were introduced during the migration from Markdown to Asciidoc.

Fix formatting

---

.github/workflows/build.yml

fixes: https://redpandadata.atlassian.net/browse/PESDLC-1556
github secrets for this repo have been migrated to aws secretsmanager. this PR uses gha [aws-actions/aws-secretsmanager-get-secrets](https://github.com/aws-actions/aws-secretsmanager-get-secrets) to access the secrets.
N/A

gha: retrieve secrets from aws sm

---

antora.yml
modules/guides/pages/serverless/about.adoc
modules/guides/pages/serverless/lambda.adoc
package-lock.json

Resolves https://github.com/redpanda-data/documentation-private/issues/#2251
Review deadline: 28 July
[Lambda guide docs preview](https://deploy-preview-16--redpanda-connect.netlify.app/redpanda-connect/guides/serverless/lambda/)

#2551 RP Connect Lambda guide updates

---

modules/guides/pages/serverless/lambda.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/#2570
Review deadline: 3 July
[Preview of Build section of Lambda guide](https://deploy-preview-17--redpanda-connect.netlify.app/redpanda-connect/guides/serverless/lambda/#build)

Fix-2570 Updated repo path to Go module

---

antora.yml
modules/cookbooks/pages/custom_metrics.adoc
modules/guides/pages/bloblang/walkthrough.adoc
modules/guides/pages/getting_started.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2594
Review deadline: 19 July
[Get Started](https://deploy-preview-22--redpanda-connect.netlify.app/redpanda-connect/guides/getting_started/)
[Custom Metrics](https://deploy-preview-22--redpanda-connect.netlify.app/redpanda-connect/cookbooks/custom_metrics/)
[Bloblang Walkthrough](https://deploy-preview-22--redpanda-connect.netlify.app/redpanda-connect/guides/bloblang/walkthrough/)

#2594 Update docker image address

---

.github/workflows/build.yml

fixes: https://redpandadata.atlassian.net/browse/PESDLC-1737
use [oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to retrieve secrets
N/A

gha: use oidc to retrieve secrets

---

local-antora-playbook.yml
package-lock.json

This PR updates the @redpanda-data/docs-extensions-and-macros package on the main branch.

auto-docs: Update extensions on main

---

modules/components/pages/processors/ollama_chat.adoc
modules/components/pages/processors/ollama_embeddings.adoc

Review deadline: 9th September

feature 2540 - Fix unclosed tags

---

modules/components/pages/processors/about.adoc

Review deadline: 9 September
N/A

2540 - Condition out categories paragraph for RPCN Cloud

---

modules/ROOT/nav.adoc
modules/cookbooks/pages/rag.adoc

Resolves https://github.com/redpanda-data/documentation-private/issues/2685 and https://redpandadata.atlassian.net/browse/CIAINFRA-354
Review deadline: end of week

cookbooks: create an AI cookbook for RAG

---

modules/cookbooks/pages/rag.adoc

Updates single source tag.
Review deadline: 11
N/A

2540 - Fix single source tagging

---

modules/ROOT/pages/about.adoc
package-lock.json

https://deploy-preview-61--redpanda-connect.netlify.app/redpanda-connect/about/#components

DOC-582 Add master connector catalog to home page

---

.github/workflows/update-extensions.yml

jira: [PESDLC-1579]
follow-up to PR #25, updates `update-extensions` to use oidc
N/A
[PESDLC-1579]: https://redpandadata.atlassian.net/browse/PESDLC-1579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: update update-extensions to use oidc

---

modules/components/pages/processors/sql_raw.adoc

https://deploy-preview-82--redpanda-connect.netlify.app/redpanda-connect/components/processors/sql_raw/#query

Update query table presentation

---

modules/ROOT/nav.adoc
modules/components/pages/outputs/timeplus.adoc

Resolves: [DOC-667](https://redpandadata.atlassian.net/browse/DOC-667)
Review deadline: 30th October
Related PR to enable Timeplus output in the Cloud: https://github.com/redpanda-data/cloud-docs/pull/102
[timeplus output](https://deploy-preview-79--redpanda-connect.netlify.app/redpanda-connect/components/outputs/timeplus/)
[DOC-667]: https://redpandadata.atlassian.net/browse/DOC-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-667 Timeplus output

---

modules/ROOT/pages/whats_new_rpcn.adoc

Review deadline: 5th November
[What's new v4.38.0](https://deploy-preview-85--redpanda-connect.netlify.app/redpanda-connect/whats_new_rpcn/)
**New connectors and telemetry service will show as broken links until put live**

DOC-667 Release details v4.38.0

---

local-antora-playbook.yml

Resolves [DOC-734](https://redpandadata.atlassian.net/browse/DOC-734)
Review deadline: 19 November
N/A
[DOC-734]: https://redpandadata.atlassian.net/browse/DOC-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-734 Update local playbook

---

modules/ROOT/nav.adoc
modules/components/pages/inputs/pg_stream.adoc

Resolves [https://github.com/redpanda-data/documentation-private/issues/<add-your-issue-number-here>](https://redpandadata.atlassian.net/browse/DOC-699)
Review deadline: 28 November
Related PR to add connector to Cloud docs: https://github.com/redpanda-data/cloud-docs/pull/140
[pg_stream input](https://deploy-preview-109--redpanda-connect.netlify.app/redpanda-connect/components/inputs/pg_stream/)

DOC-699 PostgreSQL CDC connector docs

---

modules/components/pages/outputs/aws_sqs.adoc

Resolves [DOC-806](https://redpandadata.atlassian.net/browse/DOC-806)
Review deadline: 2nd December
[aws_sqs output](https://deploy-preview-111--redpanda-connect.netlify.app/redpanda-connect/components/outputs/aws_sqs/?tab=tabs-1-advanced)
[DOC-806]: https://redpandadata.atlassian.net/browse/DOC-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-806 Add new max_records_per_request field

---

local-antora-playbook.yml
modules/ROOT/examples/playground/add-new-field.yaml
modules/ROOT/examples/playground/aggregation.yaml
modules/ROOT/examples/playground/array-processing.yaml
modules/ROOT/examples/playground/conditional-mapping.yaml
modules/ROOT/examples/playground/hello-world.yaml
modules/ROOT/examples/playground/index-access.yaml
modules/ROOT/examples/playground/merge-objects.yaml
modules/ROOT/examples/playground/metadata.yaml
modules/ROOT/examples/playground/nested-object.yaml
modules/ROOT/examples/playground/sensitive-data.yaml
modules/ROOT/examples/playground/string-manipulations.yaml
modules/ROOT/nav.adoc
modules/guides/pages/bloblang/playground.adoc
package-lock.json

This PR introduces a new interactive Bloblang playground, allowing users to experiment with Bloblang expressions in a user-friendly UI environment. The playground enables real-time Bloblang experiments, supported by a WebAssembly backend for performance and cross-browser compatibility.
Users can input JSON data, define mappings, and view the output directly in the playground interface. We also provide sample mappings that users can view and try out.
User inputs are saved to local storage so that they can leave the playground to view the reference docs and come back to continue.
The WebAssembly backend is included in a [prerelease of our UI project](https://github.com/redpanda-data/docs-ui/releases/tag/v2.1.0-alpha). As part of the bundle process, we build the `blobl.wasm` file from a …

DOC-672 Bloblang playground

---

modules/ROOT/nav.adoc
modules/components/pages/connector-support-levels.adoc
modules/get-started/pages/licensing.adoc

Resolves [DOC-790](https://redpandadata.atlassian.net/browse/DOC-790)
Review deadline: December 2nd
[Connector Support Levels](https://deploy-preview-114--redpanda-connect.netlify.app/redpanda-connect/components/connector-support-levels/)
[Licensing](https://deploy-preview-114--redpanda-connect.netlify.app/redpanda-connect/get-started/licensing/)
[DOC-790]: https://redpandadata.atlassian.net/browse/DOC-790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-790 Enterprise licensing for Redpanda Connect

---

modules/configuration/pages/secrets.adoc

Resolves [DOC-816](https://redpandadata.atlassian.net/browse/DOC-816)
Review deadline: 4th December
[Secrets](https://deploy-preview-115--redpanda-connect.netlify.app/redpanda-connect/configuration/secrets/#supported-remote-systems)
[DOC-816]: https://redpandadata.atlassian.net/browse/DOC-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-816 Specify secret management solutions

---

modules/ROOT/nav.adoc
modules/components/pages/inputs/postgres_cdc.adoc
modules/get-started/pages/whats-new.adoc

Review deadline: December 5th
Related PRs:
Cloud docs: https://github.com/redpanda-data/cloud-docs/pull/145
[postgres_cdc](https://deploy-preview-116--redpanda-connect.netlify.app/redpanda-connect/components/inputs/postgres_cdc/)

DOC-814 Rename pg_stream to postgres_cdc

---

modules/components/pages/inputs/postgres_cdc.adoc
modules/get-started/pages/whats-new.adoc

Resolves [DOC-814](https://redpandadata.atlassian.net/browse/DOC-814)
Review deadline: 6th December
Missing from original PRs for rename.
https://deploy-preview-119--redpanda-connect.netlify.app/redpanda-connect/get-started/whats-new/
https://deploy-preview-119--redpanda-connect.netlify.app/redpanda-connect/components/inputs/postgres_cdc/
[DOC-814]: https://redpandadata.atlassian.net/browse/DOC-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update what's new for connector rename

---

modules/get-started/pages/licensing.adoc

Resolves [DOC-838](https://redpandadata.atlassian.net/browse/DOC-838)
Review deadline: 6th December
[https://deploy-preview-118--redpanda-connect.netlify.app/redpanda-connect/get-started/licensing/](https://deploy-preview-118--redpanda-connect.netlify.app/redpanda-connect/get-started/licensing/)
[DOC-838]: https://redpandadata.atlassian.net/browse/DOC-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-383 Refactor licensing page

---

modules/get-started/pages/licensing.adoc
modules/get-started/pages/whats-new.adoc

Resolves [DOC-837](https://redpandadata.atlassian.net/browse/DOC-837)
Review deadline: 9th December
Related PR: [https://github.com/redpanda-data/docs/pull/900](https://github.com/redpanda-data/docs/pull/900)
https://deploy-preview-120--redpanda-connect.netlify.app/redpanda-connect/get-started/licensing/
[DOC-837]: https://redpandadata.atlassian.net/browse/DOC-837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-837 Allow trial licenses in RPCN

---

modules/components/pages/processors/benchmark.adoc

Review deadline: 16 December
[benchmark processor](https://deploy-preview-134--redpanda-connect.netlify.app/redpanda-connect/components/processors/benchmark/)

DOC-870 Benchmark processor update

---

modules/components/pages/outputs/timeplus.adoc

Resolves [DOC-879](https://redpandadata.atlassian.net/browse/DOC-879)
Review deadline: 19th December
[Timeplus output](https://deploy-preview-136--redpanda-connect.netlify.app/redpanda-connect/components/outputs/timeplus/#unstructured-messages)
[DOC-879]: https://redpandadata.atlassian.net/browse/DOC-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-879 Update code indent Timeplus output

---

modules/ROOT/nav.adoc

Resolves [DOC-637](https://redpandadata.atlassian.net/browse/DOC-637)
Review deadline: 20 December (if possible)
https://deploy-preview-138--redpanda-connect.netlify.app/redpanda-connect/home/
[DOC-637]: https://redpandadata.atlassian.net/browse/DOC-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-637 Add release notes link to reference section

---

modules/get-started/pages/upgrade/rpk-upgrade.adoc

Resolves [DOC-892](https://redpandadata.atlassian.net/browse/DOC-892)
Review deadline: 7th January
[Upgrade Redpanda Connect using rpk](https://deploy-preview-139--redpanda-connect.netlify.app/redpanda-connect/get-started/upgrade/rpk-upgrade/
)
[DOC-892]: https://redpandadata.atlassian.net/browse/DOC-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-892 Restart pipelines after upgrade or downgrade

---

local-antora-playbook.yml
modules/configuration/pages/interpolation.adoc

Review deadline: 10th January
Related PR: [https://github.com/redpanda-data/cloud-docs/pull/165](https://github.com/redpanda-data/cloud-docs/pull/165)
[Interpolation (Cloud)](https://deploy-preview-140--redpanda-connect.netlify.app/redpanda-cloud/develop/connect/configuration/interpolation/)

DOC-621 Update note text to reference contextual variables

---

modules/components/pages/inputs/aws_sqs.adoc

Resolves [DOC-903](https://redpandadata.atlassian.net/browse/DOC-903), and includes rewording of field descriptions/definitions.
Review deadline: 21st January
[`aws_sqs` input](https://deploy-preview-145--redpanda-connect.netlify.app/redpanda-connect/components/inputs/aws_sqs/)
[DOC-903]: https://redpandadata.atlassian.net/browse/DOC-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-903 Add new message fields to aws_sqs input

---

modules/components/pages/scanners/avro.adoc

Resolves [DOC-904](https://redpandadata.atlassian.net/browse/DOC-904). **Also style updates and broken links to specs**
Review deadline: 21st January
[avro scanner](https://deploy-preview-148--redpanda-connect.netlify.app/redpanda-connect/components/scanners/avro/)
[DOC-904]: https://redpandadata.atlassian.net/browse/DOC-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-904 Add metadata description for avro scanner

---

modules/components/pages/processors/ollama_chat.adoc

Resolves [DOC-926](https://redpandadata.atlassian.net/browse/DOC-926)
Review deadline: 21st January
[ollama_chat](https://deploy-preview-147--redpanda-connect.netlify.app/redpanda-connect/components/processors/ollama_chat/)
[DOC-926]: https://redpandadata.atlassian.net/browse/DOC-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-926 Added support for tool calls - ollama_chat

---

modules/components/pages/inputs/sql_raw.adoc
modules/components/pages/outputs/sql_raw.adoc
modules/components/pages/processors/sql_raw.adoc

Resolves [DOC-959](https://redpandadata.atlassian.net/browse/DOC-959)
Review deadline: 23rd January
[`sql_raw` input](https://deploy-preview-153--redpanda-connect.netlify.app/redpanda-connect/components/inputs/sql_raw/)
[`sql_raw `output](https://deploy-preview-153--redpanda-connect.netlify.app/redpanda-connect/components/outputs/sql_raw/)
[`sql_raw` processor](https://deploy-preview-153--redpanda-connect.netlify.app/redpanda-connect/components/processors/sql_raw/)
[DOC-959]: https://redpandadata.atlassian.net/browse/DOC-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-959 sql_raw updates for executing multiple queries

---

modules/configuration/pages/templating.adoc

Resolves [DOC-963](https://redpandadata.atlassian.net/browse/DOC-963)
Review deadline: 24th January
[Templating guide](https://deploy-preview-157--redpanda-connect.netlify.app/redpanda-connect/configuration/templating/)
[DOC-963]: https://redpandadata.atlassian.net/browse/DOC-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-963 Update test and type fields for templating

---

modules/ROOT/nav.adoc
modules/cookbooks/pages/snowflake_ingestion.adoc

https://deploy-preview-146--redpanda-connect.netlify.app/redpanda-connect/cookbooks/snowflake_ingestion/

cookbooks: add snowflake ingestion cookbook

---

modules/ROOT/nav.adoc
modules/components/pages/processors/ollama_chat.adoc
modules/components/pages/processors/ollama_moderation.adoc

Resolves [DOC-927](https://redpandadata.atlassian.net/browse/DOC-927)
Review deadline: 21st January
Related PR for cloud page: [https://github.com/redpanda-data/cloud-docs/pull/179](https://github.com/redpanda-data/cloud-docs/pull/179)
[ollama_moderation](https://deploy-preview-150--redpanda-connect.netlify.app/redpanda-connect/components/processors/ollama_moderation/)
[ollama_chat](https://deploy-preview-150--redpanda-connect.netlify.app/redpanda-connect/components/processors/ollama_chat/)
[DOC-927]: https://redpandadata.atlassian.net/browse/DOC-927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-927 Add ollama_moderation processor

---

modules/components/pages/outputs/snowflake_streaming.adoc

[https://deploy-preview-149--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/#account](https://deploy-preview-149--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/#account)

Add a query to determine the account field in snowflake_streaming output

---

modules/components/pages/inputs/redpanda_migrator.adoc
modules/components/pages/outputs/snowflake_streaming.adoc

Resolves [DOC-996](https://redpandadata.atlassian.net/browse/DOC-996)
Review deadline: 20th February
[snowflake_streaming output](https://deploy-preview-173--redpanda-connect.netlify.app/redpanda-connect/components/outputs/snowflake_streaming/)
[DOC-996]: https://redpandadata.atlassian.net/browse/DOC-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-996 Add schema_evolution.processors

---

modules/ROOT/nav.adoc
modules/components/pages/inputs/mysql_cdc.adoc

Resolves [DOC-820](https://redpandadata.atlassian.net/browse/DOC-820)
Review deadline: 19th February
[`mysql_cdc` input](https://deploy-preview-174--redpanda-connect.netlify.app/redpanda-connect/components/inputs/mysql_cdc/)
[DOC-820]: https://redpandadata.atlassian.net/browse/DOC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-820 `mysql_cdc` input

---

modules/get-started/pages/whats-new.adoc

Resolves [DOC-1027](https://redpandadata.atlassian.net/browse/DOC-1027)
Review deadline: 19th February
[What's new](https://deploy-preview-175--redpanda-connect.netlify.app/redpanda-connect/get-started/whats-new/)
Links to `mysql_cdc` will show as broken until the related PR is merged.
[DOC-1027]: https://redpandadata.atlassian.net/browse/DOC-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1027 What's new 4.46.0

---

modules/get-started/pages/about.adoc

Resolves #188.
Review deadline: N/A
Not sure if this change is correct. Please let me know what you think.

Fix broken links

---

.hyperlint/config.yaml
.hyperlint/reviewer/custom-style-guide/code-formatting.adoc
.hyperlint/reviewer/custom-style-guide/grammar.adoc
.hyperlint/reviewer/custom-style-guide/styles.adoc
.hyperlint/reviewer/vale-style-guide/.vale.ini
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/MeaningfulLinkText.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/OptionalPlurals.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/SentenceLength.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/SwapWords.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/We.yml
.hyperlint/reviewer/vale-style-guide/styles/CustomStyle/WeakModifiers.yml
.hyperlint/reviewer/vale-style-guide/styles/config/vocabularies/CustomVocab/accept.txt
.hyperlint/reviewer/vale-style-guide/styles/config/vocabularies/CustomVocab/reject.txt

Add Style Guide 

---

modules/components/partials/feature_stability_caution.adoc
modules/guides/pages/bloblang/methods.adoc

Resolves [DOC-1166](https://redpandadata.atlassian.net/browse/DOC-1166)
Review deadline: 7th April
[Bloblang methods](https://deploy-preview-210--redpanda-connect.netlify.app/redpanda-connect/guides/bloblang/methods/#unicode_segments)
[DOC-1166]: https://redpandadata.atlassian.net/browse/DOC-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1166 Add unicode_segments method

---

modules/get-started/pages/whats-new.adoc

Resolves [DOC-1212](https://redpandadata.atlassian.net/browse/DOC-1212)
Review deadline: 11th April
This pull request includes several updates to the documentation for new features and enhancements in version 4.50.0. The most important changes include the introduction of agentic behavior to the `openai_chat_completion` processor, support for special FLOAT values in the `snowflake_streaming` output, and the addition of new fields to various outputs.
* Introduced agentic behavior to the `openai_chat_completion` processor, allowing the specification of external tools to enrich OpenAI large language model responses.
* Added support for special FLOAT values (NaN, -inf, inf) in the `snowflake_streaming` output.
* Added the `translate_ids` field to the `schema_registry` output and the …

DOC-1212 What's new for 4.50.0

---

modules/components/pages/processors/cohere_chat.adoc

Resolves [DOC-1313](https://redpandadata.atlassian.net/browse/DOC-1313)
Review deadline: 14 May
This pull request updates the documentation for the `cohere_chat` processor, introducing new configuration fields and enhancing descriptions for better clarity and functionality. The most significant changes include the addition of the `max_tool_calls` and `tools` fields, extended documentation for tool-related configurations, and improvements to existing text for consistency and readability.
* Added `max_tool_calls` to specify the maximum number of tool calls the model can perform. [[1]](diffhunk://#diff-08eccb7077fba09d6721573f5c9fdd5e7f88723bda6ad4f27423e1a20786e8bcR34-R42) [[2]](diffhunk://#diff-08eccb7077fba09d6721573f5c9fdd5e7f88723bda6ad4f27423e1a20786e8bcR85-R91) …

DOC-1313 Adds tool section to cohere_chat processor

---

modules/ROOT/nav.adoc
modules/get-started/pages/whats-new.adoc
modules/plugins/pages/about.adoc
package-lock.json

This plugin framework allows you to create and load plugins at runtime, opening up a world of new integration possibilities beyond Go.
* **New Plugins Section**: Added a comprehensive `about.adoc` page under `plugins`, detailing Redpanda Connect's dynamic plugin framework. 
* **Navigation Update**: Added a new entry to the navigation file (`nav.adoc`) to link to the newly created Plugins documentation.
[Plugins](https://deploy-preview-257--redpanda-connect.netlify.app/redpanda-connect/plugins/about/)

Plugins doc

---

modules/components/pages/processors/protobuf.adoc

Resolves linking to protobuf processor examples

correct include for protobuf connector examples

---

modules/components/pages/scanners/json_array.adoc

Add version for json_array

---

modules/components/pages/inputs/postgres_cdc.adoc

Needed for the heartbeat implementation

update postgres version
